# Generated by Django 5.1.2 on 2024-10-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_account_employee_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='salary_structure',
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
    ]
