# Generated by Django 5.1.2 on 2024-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerprint_file',
            field=models.FileField(blank=True, null=True, upload_to='fingerprints/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
