# Generated by Django 5.1.2 on 2024-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_fingerprint_file_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sss_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
