# Generated by Django 5.1.2 on 2024-11-08 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_sss_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time_in',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_out',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
