# Generated by Django 5.1.2 on 2024-11-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='fingerprint_data',
        ),
        migrations.AddField(
            model_name='attendance',
            name='fingerprint_file',
            field=models.FileField(blank=True, null=True, upload_to='attendance_fingerprints/'),
        ),
    ]
