# Generated by Django 5.1.2 on 2024-11-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_attendance_fingerprint_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
