# Generated by Django 5.1.2 on 2024-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendance_total_wage_employee_daily_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('announcement_image', models.ImageField(blank=True, null=True, upload_to='announcement_image/')),
            ],
        ),
    ]
