# Generated by Django 5.1.2 on 2025-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payroll_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='picture_time_out',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_pictures/'),
        ),
    ]
